// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1583355217);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1583355337);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1583350879);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1583355097);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1583355521);
user_pref("browser.cache.disk.amount_written", 992);
user_pref("browser.cache.disk.capacity", 675840);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "US");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 03 Mar 2020 10:57:36 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1583355217);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200110142707");
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"0f5f2c70-2bb1-4785-ac42-ba9fd7456334\",\"default-theme@mozilla.org\":\"6be0ec3e-e570-4f6a-b99f-c82bdd97ec25\",\"google@search.mozilla.org\":\"94c70185-322b-4cb9-bbd0-fdc77cc8dc95\",\"amazondotcom@search.mozilla.org\":\"0237dfbe-fd4d-48a5-bc51-a3e8f8bbc5f7\",\"bing@search.mozilla.org\":\"c0bb165b-191c-4570-8323-2c551df7d5ed\",\"ddg@search.mozilla.org\":\"b607180e-3ceb-46b9-adb3-70c3078f25b1\",\"twitter@search.mozilla.org\":\"e66d613d-94db-4d49-bb8f-55f135034a01\",\"wikipedia@search.mozilla.org\":\"93423162-3d81-49b7-8f50-ca41fec2feaf\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1583358987);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "32782cce-9de0-41e7-9c22-c96228f120c");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1583269129);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "0dc63b94-4825-4725-9c64-726cb64b0267");
user_pref("services.blocklist.pinning.checked", 1583355097);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1583344365865\"");
user_pref("services.settings.last_update_seconds", 1583355097);
user_pref("services.settings.main.hijack-blocklists.last_check", 1583355097);
user_pref("services.settings.main.language-dictionaries.last_check", 1583355097);
user_pref("services.settings.main.sites-classification.last_check", 1583355097);
user_pref("services.settings.security.onecrl.checked", 1583355097);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1583269129);
user_pref("toolkit.telemetry.cachedClientID", "69141d72-5a57-4d12-aca1-8d149f29eb0d");
user_pref("toolkit.telemetry.prompted", 2);
